[package]
name = "corodaw-egui"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.3"
engine = { path = "../engine" }
project = { path = "../project" }
smol.workspace = true
winit = "0.30.12"
