[package]
name = "corodaw-egui"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_app.workspace = true
bevy_ecs.workspace = true
eframe = "0.33.3"
engine = { path = "../engine" }
project = { path = "../project" }
rfd = "0.17.2"
smol.workspace = true
winit = "0.30.12"
