[workspace]
resolver = "3"
members = [
  "crates/audio-graph",
  "crates/corodaw-egui",
  "crates/corodaw-gpui",
  "crates/engine",
  "crates/project"
]
default-members = ["crates/corodaw-gpui"]

[workspace.dependencies]
anyhow = "1.0.100"
audio-blocks = "0.5.0"
bevy_app = "0.18.0"
bevy_ecs = "0.18.0"
clack-extensions = { package = "clack-extensions", git = "https://github.com/prokopyl/clack.git", features = [
  "audio-ports",
  "clack-host",
  "gui",
  "log",
  "note-ports",
  "params",
  "raw-window-handle_06",
  "timer"
] }
clack-host = { package = "clack-host", git = "https://github.com/prokopyl/clack.git" }
cpal = "0.17.0"
derivative = "2.2.0"
futures = "0.3.31"
futures-channel = "0.3.31"
gpui = "0.2.2"
gpui-component = "0.5.0"
raw-window-handle = "0.6.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
smol = "2.0.2"
thiserror = "2.0.18"
uuid = { version = "1", features = ["serde", "v4"] }
wmidi = "4.0.6"
