[package]
name = "corodaw-gpui"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
audio-graph = { path = "../audio-graph" }
engine = { path = "../engine" }
gpui.workspace = true
gpui-component.workspace = true
