[package]
name = "project"
version = "0.1.0"
edition = "2024"

[dependencies]
audio-graph = { path = "../audio-graph" }
derivative.workspace = true
engine = { path = "../engine" }
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
