[package]
name = "corodraw"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
gpui-component.workspace = true
gpui.workspace = true
clack-host = {git = "https://github.com/prokopyl/clack.git", package="clack-host" }
dirs = "6.0.0"
walkdir = "2.5.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
