[package]
name = "corodraw"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
audio-blocks = "0.5.0"
clack-extensions = { package = "clack-extensions", git = "https://github.com/prokopyl/clack.git", features = [
  "audio-ports",
  "clack-host",
  "gui",
  "log",
  "params",
  "raw-window-handle_06",
  "timer"
] }
clack-host = { package = "clack-host", git = "https://github.com/prokopyl/clack.git" }
cpal = "0.17.0"
dirs = "6.0.0"
futures = "0.3.31"
futures-channel = "0.3.31"
gpui.workspace = true
gpui-component.workspace = true
rand = "0.9.2"
raw-window-handle = "0.6.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
walkdir = "2.5.0"
