[package]
name = "corodraw"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
clack-extensions = { package = "clack-extensions", git = "https://github.com/prokopyl/clack.git", features = [
  "clack-host",
  "gui",
  "log",
  "raw-window-handle_06",
] }
clack-host = { package = "clack-host", git = "https://github.com/prokopyl/clack.git" }
dirs = "6.0.0"
futures = "0.3.31"
futures-channel = "0.3.31"
gpui.workspace = true
gpui-component.workspace = true
raw-window-handle = "0.6.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
walkdir = "2.5.0"
