[package]
name = "corodaw"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
clack-extensions.workspace = true
cpal.workspace = true
engine = { path = "../engine" }
futures.workspace = true
futures-channel.workspace = true
gpui.workspace = true
gpui-component.workspace = true
plugin-ui-host = { path = "../plugin-ui-host" }
raw-window-handle.workspace = true
